Create iplayer_data_c2
Came across an issue quite early on. Starting at line 85

raise KeyError("Column not found: {key}".format(key=key))

KeyError: 'Column not found: percentage_watched'

# We need to consider here only the "past data", i.e. get rid of the last twoweek obs
# which corresponds to our target
features=pivot_data(data[data['twoweek']<8])
features.reset_index().head()